image:
  repository: fluent/fluent-bit
  tag: latest
  pullPolicy: Always

namespace: dev

fluentbit:
  flush: 5
  logLevel: info
  memBufLimit: 50MB
  db: /var/lib/fluent-bit/flb_kube.db
  filterNamespace: dev

elasticsearch:
  host: 4b278f25cb7141c3b1d82ec253b37b1b.us-central1.gcp.cloud.es.io
  port: 443
  tls: true
  credentialsSecret: fluent-bit-elastic-credentials

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
